### PR TITLE
github request

### PR DESCRIPTION
**Pull request by NGFuture**
Homework 6-1 - github request

### CODE REVIEW

**Comment by ginestah** [comment]
Thank you for editing comment access! Great job on everything, I love that you used forEach instead of a for loop for this, that was great! The only time I use a for loop is if I need to break out of it for some reason and don't want to iterate over every index. Just one critique is that there are a lot of console.logs, I would get rid of or comment them out when you are done using them to debug/look at data, as the dev tools look a little bit messy right now. Great work!

**Comment by NGFuture** [comment]
Thank you for feedback! I will clean up the code a little bit before
submitting the final project! Have you received all of my homeworks? I hope
everything came through Squibby, at least I've submitted everything...



чт, 8 июл. 2021 г. в 06:53, Huckleberry Ginesta ***@***.***>:

**Comment by ginestah** [comment]
I am only working on this and future homeworks, if you got feedback from a previous grader you should be all set! Let me know if you didn't and I can look into it.

**Comment by NGFuture** [comment]
Oh, I got it. But I have not received feedback for quit a lot of homeworks
so if you could just check if all previous ones are marked as submitted I
would appreciate it!

**Comment by ginestah** [comment]
yes you are marked as on track as far as I can tell :) I wouldn't worry about it at all. I guess whoever was looking at your homework before just didn't give feedback.

**Pull request merged**
